site_name: Isik's Tech Documentation
site_url: https://docs.isiks.tech
site_author: XBST LLC
copyright: Copyright &copy; 2026 XBST LLC
repo_url: https://github.com/xbst
repo_name: Isik's Tech GitHub

theme:
  name: material
  logo: assets/isikstech_tp.png
  favicon: assets/isikstech_tp.ico
  icon:
    repo: material/github
    admonition:
      warning: octicons/alert-16
      note: octicons/tag-16
      success: octicons/check-16
      tip: octicons/squirrel-16
      failure: octicons/x-circle-16
      quote: octicons/quote-16
      
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.code.copy
    
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: amber
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: amber
      accent: amber
      
extra_css:
  - assets/stylesheets/extra.css
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.superfences
  - sane_lists
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji ""
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg ""
  - admonition
  - pymdownx.details
  - md_in_html
  - pinout_embed

plugins:
  - redirects:
      redirect_maps:
        Ouroboros/gibberish.md: ouroboros/plugin-reference.md
        Birds-Nests/Birds-Nest/Birds-Nest-Manual.md: birds-nest/usb/manual.md
        Birds-Nests/Birds-Nest-CAN/Birds-Nest-CAN-Manual.md: birds-nest/can/manual.md
        Box-Turtle-Controllers/AFC-Lite/AFC-Lite-Manual.md: box-turtle/afc-lite/manual.md
        Box-Turtle-Controllers/AFC-Pro/AFC-Pro-Manual.md: box-turtle/afc-pro/manual.md
        Hedgehog/Hedgehog.md: hedgehog/manual.md
        KUSBA/KUSBA-manual.md: kusba/manual.md
        KUSBA/KUSBA-Pro/ADXL345.md: kusba/pro/adxl345.md
        KUSBA/KUSBA-Pro/LIS2DW.md: kusba/pro/lis2dw.md
        KUSBA/KUSBA-Pro/Mount.md: kusba/pro/mount.md
        MOAR_CAN/MOAR_CAN-Manual.md: moar-can/manual.md
        Nevermore/Controller.md: nevermore/controller.md
        Nevermore/Firmware-Setup.md: nevermore/firmware-setup.md
        Nevermore/Max-2-PCB.md: nevermore/max-2-pcb.md
        Nevermore/SM-PCB.md: nevermore/sm-pcb.md
        Nevermore/SM2-PCB.md: nevermore/sm2-pcb.md
        Nevermore/SM3-PCB.md: nevermore/sm3-pcb.md
        Ouroboros/Beta1-Stepper-Calibration.md: ouroboros/beta1-stepper-calibration.md
        Ouroboros/Firmware-Setup.md: ouroboros/firmware-setup.md
        Ouroboros/IT.md: ouroboros/it.md
        Ouroboros/Plugin-Reference.md: ouroboros/plugin-reference.md
        Ouroboros/Sensorless-Homing.md: ouroboros/sensorless-homing.md
        Ouroboros/Stepper-Calibration.md: ouroboros/stepper-calibration.md
        Ouroboros/wiring.md: ouroboros/wiring.md
        ToqueCAN/ToqueCAN-Manual.md: toquecan/manual.md
        PiCAN.md: pican/manual.md
        pican.md: pican/manual.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-D9R9ZZFJKC
  social:
    - icon: material/youtube
      link: https://www.youtube.com/c/isikstech
      name: Isik's Tech YouTube Channel
    - icon: material/twitter
      link: https://twitter.com/IsiksTech
      name: Isik's Tech Twitter Page
    - icon: material/github
      link: https://github.com/xbst
      name: Isik's Tech Github Profile
    - icon: simple/discord
      name: Isik's Tech Discord Server
      link: https://discord.gg/dNd5fB74J7
    - icon: material/store
      link: https://store.isiks.tech
      name: Official Isik's Tech Store

nav:
  - index.md
  - "Birds' Nest Boards":
    - "Birds' Nest (USB)":
      - "Manual": "birds-nest/usb/manual.md"
      - "GitHub Repository": "https://github.com/xbst/Birds-Nest/"
      - "Store Page": "https://store.isiks.tech/products/birds-nest"
    - "Birds' Nest CAN":
      - "Manual": "birds-nest/can/manual.md"
      - "GitHub Repository": "https://github.com/xbst/Birds-Nest-CAN/"
      - "Store Page": "https://store.isiks.tech/products/birds-nest-CAN"
  - "Filament Changer Controllers":
    - "AFC-Lite":
      - "Manual": "box-turtle/afc-lite/manual.md"
      - "GitHub Repository": "https://github.com/xbst/AFC-Lite/"
      - "Store Page": "https://store.isiks.tech/products/AFC-Lite"
    - "AFC-Pro":
      - "Manual": "box-turtle/afc-pro/manual.md"
      - "GitHub Repository": "https://github.com/xbst/AFC-Pro/"
      - "Store Page": "https://store.isiks.tech/products/AFC-Pro"
    - "OwlFC-Mini":
      - "Manual": "owlfc-mini/manual.md"
      - "GitHub Repository": "https://github.com/xbst/OwlFC-Mini/"
      - "Store Page": "https://store.isiks.tech/products/owlfc-mini"
  - "Hedgehog":
    - "Manual": "hedgehog/manual.md"
    - "Store Page": "https://store.isiks.tech/products/hedgehog"
  - "KUSBA":
    - KUSBA:
      - "Instructions": "kusba/manual.md"
      - "GitHub Repository": "https://github.com/xbst/KUSBA/"
      - "Store Page": "https://store.isiks.tech/products/kusba-klipper-usb-accelerometer"
    - KUSBA Pro:
      - "Instructions":
        - "LIS2DW Instructions": "kusba/pro/lis2dw.md"
        - "ADXL345 Instructions": "kusba/pro/adxl345.md"
        - "Mount Assembly": "kusba/pro/mount.md"
      - "GitHub Repository": "https://github.com/xbst/KUSBA-PRO/"
      - "Store Page": "https://store.isiks.tech/products/KUSBA-PRO"
  - "Nevermore Electronics":
    - "Nevermore PCBs":
      - "Nevermore PCBs": "nevermore/controller.md"
      - "Mounts & Wiring":
        - "Max 2 PCB": "nevermore/max-2-pcb.md"
        - "Mini & Stealthmax PCB": "nevermore/sm-pcb.md"
        - "Stealthmax PCB 2": "nevermore/sm2-pcb.md"
        - "Stealthmax PCB 3": "nevermore/sm3-pcb.md"
      - "Firmware & Software Setup": "nevermore/firmware-setup.md"
    - "Nevermore BME280 & SGP40 Sensors": "https://github.com/xbst/Nevermore-Sensors"
    - "Store Pages":
      - "Nevermore Max PCB": "https://store.isiks.tech/products/nevermore-max-controller-pcb"
      - "Nevermore Mini & Stealthmax PCB": "https://store.isiks.tech/products/nevermore-stealthmax-pcb"
      - "Nevermore Stealthmax PCB 3": "https://store.isiks.tech/products/nevermore-stealthmax-pcb-3"
      - "Nevermore Sensors": "https://store.isiks.tech/products/bme280-sgp40-air-quality-sensors-for-nevermore-air-filters"
  - "PiCAN":
    - "Manual": "pican/manual.md"
    - "GitHub Repository": "https://github.com/xbst/PiCAN"
    - "Store Page": "https://store.isiks.tech/products/pican-usb-to-can-bus-adapter"
  - "ToqueCAN":
    - "Manual": "toquecan/manual.md"
    - "GitHub Repository": "https://github.com/xbst/ToqueCAN/"
    - "Store Page": "https://store.isiks.tech/products/toquecan"
  - "MOAR_CAN":
    - "Manual": "moar-can/manual.md"
    - "GitHub Repository": "https://github.com/xbst/MOAR_CAN"
    - "Store Page": "https://store.isiks.tech/products/MOAR_CAN"
  - "Ouroboros":
    - "Mount & Wiring": "ouroboros/wiring.md"
    - "Firmware Setup": "ouroboros/firmware-setup.md"
    - "Motor Setup":
      - "Stepper Motors": "ouroboros/stepper-calibration.md"
    - "Other Docs":
        - "Sensorless Homing": "ouroboros/sensorless-homing.md"
        - ouroboros/plugin-reference.md
    - "Store Page": "https://store.isiks.tech/products/ouroboros"
